version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - .:/app
    networks:
      - react-net
    restart: always

networks:
  react-net:
    driver: bridge
